"""Generate `DeviceType` from the Matter data model's device type XML.

Usage: matter-device-types.py <data_model/<version>> <output.rs>

Every device type with an id becomes a variant. A server-side cluster the
Device Library marks `mandatoryConform` with no condition is recorded as
mandatory; everything else the type lists is optional or excluded and is
not emitted, since nothing consumes it yet.
"""

import glob
import os
import re
import sys
import xml.etree.ElementTree as ET

SKIPPED_CONFORMANCE = {"disallowConform", "deprecateConform", "provisionalConform"}


def variant_name(name):
    words = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(w[:1].upper() + w[1:].lower() for w in words if w)


def load(data_model):
    with open(os.path.join(data_model, "spec_sha")) as f:
        spec_sha = f.read().strip()

    types = []
    for path in sorted(glob.glob(os.path.join(data_model, "device_types", "*.xml"))):
        root = ET.parse(path).getroot()
        if root.tag != "deviceType":
            continue
        raw_id = root.get("id") or ""
        if not raw_id.startswith("0x"):
            continue
        type_id = int(raw_id, 16)
        name = root.get("name")

        mandatory = []
        clusters = root.find("clusters")
        for cluster in clusters if clusters is not None else []:
            if cluster.get("side") != "server":
                continue
            conformance = [c for c in cluster if c.tag.endswith("Conform")]
            if len(conformance) != 1:
                raise SystemExit(
                    f"{path}: cluster {cluster.get('name')} has "
                    f"{len(conformance)} conformance elements"
                )
            conform = conformance[0]
            if conform.tag == "mandatoryConform" and len(conform) == 0:
                mandatory.append(int(cluster.get("id"), 16))
        types.append((type_id, name, variant_name(name), sorted(set(mandatory))))

    types.sort()
    ids = [t[0] for t in types]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate device type ids")
    variants = [t[2] for t in types]
    if len(variants) != len(set(variants)):
        raise SystemExit("device type names collide after CamelCasing")
    return spec_sha, types


def render(version, spec_sha, types):
    out = []
    w = out.append
    w("//! Matter device types, generated from the Matter data model.")
    w("//!")
    w("//! Generated by `nix build .#matter-device-types` from the")
    w(f"//! `data_model/{version}` directory of connectedhomeip at spec")
    w(f"//! revision `{spec_sha}`. Do not edit by hand: the")
    w("//! `matter-device-types` flake check compares this file against the")
    w("//! generator's output and prints the command that refreshes it.")
    w("")
    w("use serde::Deserialize;")
    w("use serde::Serialize;")
    w("")
    w("/// A device type from the Matter Device Library, as an endpoint's")
    w("/// Descriptor cluster would list it.")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, facet::Facet)]")
    w("#[repr(u16)]")
    w("pub enum DeviceType {")
    for type_id, _, variant, _ in types:
        w(f"    {variant} = 0x{type_id:04X},")
    w("}")
    w("")
    w("impl DeviceType {")
    w("    /// Matter device type ID.")
    w("    pub fn id(self) -> u16 {")
    w("        self as u16")
    w("    }")
    w("")
    w("    /// The name the Device Library gives this type.")
    w("    pub fn name(self) -> &'static str {")
    w("        match self {")
    for _, name, variant, _ in types:
        w(f'            DeviceType::{variant} => "{name}",')
    w("        }")
    w("    }")
    w("")
    w("    /// Server clusters every endpoint of this type must carry, by")
    w("    /// cluster ID. Conditional and optional clusters are not listed.")
    w("    pub fn mandatory_clusters(self) -> &'static [u32] {")
    w("        match self {")
    for _, _, variant, mandatory in types:
        ids = ", ".join(f"0x{c:04X}" for c in mandatory)
        w(f"            DeviceType::{variant} => &[{ids}],")
    w("        }")
    w("    }")
    w("}")
    w("")
    return "\n".join(out)


def main():
    data_model, output = sys.argv[1:]
    version = os.path.basename(os.path.normpath(data_model))
    spec_sha, types = load(data_model)
    with open(output, "w") as f:
        f.write(render(version, spec_sha, types))


if __name__ == "__main__":
    main()
