#[cfg(feature = "integration_ecoflow")]
pub mod ecoflow;
#[cfg(feature = "integration_metno")]
pub mod metno;
#[cfg(feature = "integration_mqtt")]
pub mod mqtt;
#[cfg(feature = "integration_snapcast")]
pub mod snapcast;
#[cfg(feature = "integration_wake_on_lan")]
pub mod wake_on_lan;
